### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by droegier** [pauloamgomes/contentful-json-inspector#13]
Hi

I can't get the extension to work. Here is my config, but the expected section in the right tab does not appear.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/16133184/156025273-7d4b67d7-cacc-4f17-87d5-2da4d3bcc446.png">

Any help? Thanks!

**Comment by pauloamgomes** [comment]
Hi @droegier , this is a old UI extension but anyway it should still work, can you try to enable the "legacy sidebar extension" option?

**Comment by roman-yarovoy** [comment]
FYI, WIth "legacy sidebar extension" it works, just need to enable it in sidebar.
<img width="882" alt="Screen Shot 2022-03-31 at 19 00 28" src="https://user-images.githubusercontent.com/1466667/161110891-76ec64c4-cd69-492d-87a3-20674abfaf1d.png">
